# Generated by Django 2.0 on 2018-05-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20, verbose_name='会员帐号')),
                ('username', models.CharField(max_length=20, verbose_name='会员姓名')),
                ('password', models.CharField(max_length=20, verbose_name='会员密码')),
                ('cell_phone', models.CharField(max_length=11, verbose_name='会员手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='会员邮箱')),
                ('ident_id', models.CharField(max_length=18, verbose_name='会员身份证号')),
                ('is_turbo', models.BooleanField(choices=[(True, '是'), (False, '不是')], verbose_name='是否是协会会员')),
                ('is_valid', models.BooleanField(choices=[(True, '启用'), (False, '不启用')], verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '注册会员',
            },
        ),
    ]
